# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-24 01:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(blank=True, max_length=255)),
                ('apellido', models.CharField(blank=True, max_length=255)),
                ('dni', models.CharField(blank=True, max_length=15)),
                ('telefono', models.CharField(blank=True, max_length=20)),
                ('empresa', models.CharField(blank=True, max_length=255)),
                ('cif', models.CharField(blank=True, max_length=20)),
                ('email', models.CharField(blank=True, max_length=50)),
                ('telefono1', models.CharField(blank=True, max_length=20)),
                ('ciudad', models.CharField(blank=True, max_length=100)),
                ('provincia', models.CharField(blank=True, max_length=100)),
                ('direccion', models.CharField(blank=True, max_length=100)),
                ('codpostal', models.CharField(blank=True, max_length=10)),
                ('thumbnail', models.ImageField(default='pic_folder/None/no-img.jpg', upload_to='pic_folder_clientes/')),
                ('created_at', models.DateTimeField(editable=False)),
            ],
        ),
    ]
