# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-24 23:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='thumbnail',
            field=models.ImageField(default='pic_folder_productos/None/no-image.png', upload_to='pic_folder_productos/'),
        ),
    ]
