# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-25 15:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0003_templates'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producto',
            name='precio_currency',
        ),
        migrations.AlterField(
            model_name='producto',
            name='precio',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
