# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-24 01:49
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telefono', models.CharField(blank=True, max_length=20)),
                ('tipo', models.CharField(blank=True, choices=[(b'Ventas', b'Ventas'), (b'Consultoria', b'Consultoria'), (b'Mercadeo', b'Mercadeo'), (b'Administacion', b'Administacion'), (b'Sistemas', b'Sistemas')], max_length=20)),
                ('thumbnail', models.ImageField(default=b'pic_folder/None/no-img.jpg', upload_to=b'pic_folder_vendedores/')),
                ('created_at', models.DateTimeField(editable=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
