# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-26 15:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='thumbnail',
            field=models.ImageField(default=b'pic_folder/None/no-img.png', upload_to=b'pic_folder_vendedores/'),
        ),
    ]
